apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-app
  type: NodePort # Cambia a NodePort
  ports:
    - protocol: TCP
      port: 3000     # Puerto del servicio
      targetPort: 3000 # Puerto en el contenedor de la aplicación React
      nodePort: 30080  # Puerto en el que será accesible el servicio en tu máquina local
